import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";

// Create an API using createApi
export const apis = createApi({
   reducerPath: "apis", // Define a reducer path for your API state
   baseQuery: fetchBaseQuery({ baseUrl: "https://api.coingecko.com/api/v3" }), // Define the base URL for your API requests
   tagTypes: ["SideBarData", "PortfolioData", "ExchangeData"], // Define tag types for caching

   // Define endpoints for your API
   endpoints: (builder) => ({
      // Define an endpoint for getting sidebar data
      getSideBarData: builder.query({
         query: (url) => `${url}`, // Define a function to build the query URL
         providesTags: ["SideBarData"], // Define tags for caching
      }),

      // Define an endpoint for getting portfolio data
      getPortfolioData: builder.query({
         query: (url) => `${url}`, // Define a function to build the query URL
         providesTags: ["PortfolioData"], // Define tags for caching
      }),

      // Define an endpoint for getting exchange data
      getExhangeData: builder.query({
         query: (url) => `${url}`, // Define a function to build the query URL
         providesTags: ["ExchangeData"], // Define tags for caching
      })
   })
})

// Export query hooks generated by the API
export const { useGetSideBarDataQuery, useGetPortfolioDataQuery, useGetExhangeDataQuery } = apis;
